/**
 * Images live in a sidecar folder inside the user's writing folder, beside the
 * `.md` files, and the Markdown carries an ordinary relative link:
 *
 *   2026-09-10-142233-a1b2.md    ![](attachments/2026-09-10-142233-a1b2-1.png)
 *   attachments/
 *     2026-09-10-142233-a1b2-1.png
 *
 * This is the only shape that keeps all three product rules at once. The `.md`
 * still opens correctly in Obsidian or iA Writer, the bytes never leave the
 * folder the user picked, and moving or syncing that folder keeps the images
 * working because the reference is relative rather than absolute.
 *
 * Data URIs were the obvious alternative and are the wrong one: autosave
 * rewrites the whole body 600ms after the last keystroke and every snapshot is
 * another full copy, so one 3MB screenshot becomes megabytes of rewrites into
 * a synced folder.
 *
 * Every filename starts with the id of the entry that owns it. That is what
 * lets deleting an entry delete its images exactly, by name, with no reference
 * counting to get wrong.
 */

/** Sidecar folder name, relative to the writing folder. */
export const ASSET_DIR = 'attachments'

/** Used when a name arrives with no usable extension. See assetExtension. */
export const DEFAULT_ASSET_EXTENSION = 'bin'

/** Real extensions are three or four characters; this is only a stop. */
const MAX_EXTENSION_LENGTH = 12

/** Ids are generated by newEntryId, but this is a public entry point. */
const MAX_ENTRY_ID_LENGTH = 128

/**
 * A filename component we are willing to put on disk: must begin with a letter
 * or a digit, so `.`, `..` and dotfiles are all excluded, and may then contain
 * only characters that mean nothing to a shell, a path parser or a URL.
 */
const SAFE_COMPONENT = /^[A-Za-z0-9][A-Za-z0-9._-]*$/

/**
 * `<entryId>-<index>.<ext>`. One trailing group of digits is the index, so an
 * entry whose own id ends in `-1` is still told apart from the first image of
 * the entry whose id is the rest of it.
 */
const ASSET_FILENAME = /^(.+)-(\d+)\.([A-Za-z0-9]+)$/

/**
 * `name` reaches us from a dropped file or a clipboard item, so it is hostile
 * input on its way into a path join: `../../../.ssh/authorized_keys` must not
 * be able to walk out of the attachments folder, and a NUL or a newline must
 * never reach the filesystem at all.
 *
 * Only the extension survives. The stored name is built from the entry id and
 * an index, so nothing else in `name` is needed, and refusing to carry it
 * forward means there is no encoding, normalisation or length question left to
 * get wrong.
 */
export function assetExtension(name: string): string {
  // Take the last path segment first: an extension found before a separator
  // belongs to a directory, not to the file.
  const segments = name.split(/[/\\]/)
  const last = segments[segments.length - 1] ?? ''

  const dot = last.lastIndexOf('.')
  // `> 0` and not `>= 0`: `.gitignore` is a name without an extension, and
  // reading `gitignore` off it would be wrong.
  if (dot <= 0) return DEFAULT_ASSET_EXTENSION

  const raw = last.slice(dot + 1).toLowerCase()
  // Anything outside this set is dropped rather than escaped. Control
  // characters, spaces, dots and separators cannot survive it, which is the
  // whole point.
  const cleaned = raw.replace(/[^a-z0-9]/g, '').slice(0, MAX_EXTENSION_LENGTH)
  return cleaned === '' ? DEFAULT_ASSET_EXTENSION : cleaned
}

/**
 * The entry id becomes part of a path and part of the deletion rule, so a bad
 * one is refused rather than repaired: a silently mangled id would write
 * images that removeAssets could never find again.
 */
export function assertSafeEntryId(entryId: string): void {
  if (entryId.length > MAX_ENTRY_ID_LENGTH || !SAFE_COMPONENT.test(entryId)) {
    throw new Error(`Unsafe entry id for an attachment: ${JSON.stringify(entryId)}`)
  }
}

/** `<entryId>-<index>.<ext>`, the only filename shape this app writes. */
export function assetFilename(entryId: string, index: number, name: string): string {
  assertSafeEntryId(entryId)
  if (!Number.isSafeInteger(index) || index < 1) {
    throw new Error(`Attachment index must be a positive integer, got ${index}`)
  }
  return `${entryId}-${index}.${assetExtension(name)}`
}

/**
 * The href is the exact string that goes into the Markdown, so it is relative
 * and forward-slashed on every platform. A Windows separator here would break
 * the link everywhere else the folder is opened, and the folder is meant to
 * survive being synced between machines.
 */
export function assetHref(filename: string): string {
  return `${ASSET_DIR}/${filename}`
}

/**
 * The inverse, and deliberately strict. An href read back out of a Markdown
 * body is arbitrary text about to be joined onto the user's folder path, so
 * anything that is not exactly `attachments/<one safe filename>` is refused
 * rather than repaired.
 */
export function assetFilenameFromHref(href: string): string | null {
  // `./attachments/x.png` is the same link; some editors write it that way.
  const trimmed = href.startsWith('./') ? href.slice(2) : href
  const prefix = `${ASSET_DIR}/`
  if (!trimmed.startsWith(prefix)) return null

  const filename = trimmed.slice(prefix.length)
  if (!SAFE_COMPONENT.test(filename)) return null
  return filename
}

/** The entry that owns this file, or null if we did not write it. */
export function assetEntryId(filename: string): string | null {
  return ASSET_FILENAME.exec(filename)?.[1] ?? null
}

/** The number in `<entryId>-<index>.<ext>`, or null if we did not write it. */
export function assetIndex(filename: string): number | null {
  const raw = ASSET_FILENAME.exec(filename)?.[2]
  return raw === undefined ? null : Number(raw)
}

export function isAssetOf(filename: string, entryId: string): boolean {
  return assetEntryId(filename) === entryId
}

/**
 * `<entryId>-<n>.<ext>` is not a distinctive enough shape to be certain a file
 * is ours. An entry id is whatever the `.md` was called, so a user's own
 * `2026-09-10.md` dropped into the attachments folder parses as entry
 * `2026-09`'s tenth image. That folder sits inside their writing folder, and
 * this app does not delete writing, so Markdown is never ours to remove.
 *
 * Nothing here ever writes a `.md` attachment, so the only files this refuses
 * are files we did not put there. One that somehow got written still shows up
 * in orphanedAssets once its entry is gone, for the user to deal with.
 */
const NEVER_OURS = new Set(['md', 'markdown'])

export function isRemovableAsset(filename: string, entryId: string): boolean {
  return isAssetOf(filename, entryId) && !NEVER_OURS.has(assetExtension(filename))
}

/**
 * Numbering continues past the highest index already stored rather than
 * counting what is there, so deleting image 2 of 3 and pasting again writes a
 * fourth file instead of overwriting the third.
 */
export function nextAssetIndex(filenames: readonly string[], entryId: string): number {
  let highest = 0
  for (const filename of filenames) {
    if (!isAssetOf(filename, entryId)) continue
    const index = assetIndex(filename)
    if (index !== null && index > highest) highest = index
  }
  return highest + 1
}

/**
 * Assets whose entry no longer exists. Deleting an entry deletes its images as
 * it goes, so this only turns up what an interrupted delete or an edit made in
 * another editor left behind.
 *
 * Anything we cannot prove we wrote is left alone. The attachments folder is
 * inside the user's writing folder, and a file we do not recognise is far more
 * likely to be theirs than to be our litter.
 */
export function orphanedAssets(
  hrefs: readonly string[],
  liveEntryIds: Iterable<string>,
): string[] {
  const live = new Set(liveEntryIds)
  return hrefs.filter((href) => {
    const filename = assetFilenameFromHref(href)
    if (filename === null) return false
    const entryId = assetEntryId(filename)
    return entryId !== null && !live.has(entryId)
  })
}

/**
 * Both adapters hand back raw bytes and the caller turns them into a blob URL.
 * A Blob with no type serves as application/octet-stream, and the extension is
 * the only type information a sidecar file carries, so the mapping has to live
 * somewhere: here, next to the code that chose the extension.
 */
const MIME_TYPES: Record<string, string> = {
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  webp: 'image/webp',
  avif: 'image/avif',
  bmp: 'image/bmp',
  svg: 'image/svg+xml',
  tif: 'image/tiff',
  tiff: 'image/tiff',
  heic: 'image/heic',
  heif: 'image/heif',
}

export function assetMimeType(nameOrHref: string): string {
  const extension = assetExtension(nameOrHref)
  return MIME_TYPES[extension] ?? 'application/octet-stream'
}
